export const OrderStatus = Object.freeze({
  UNASSIGNED: "UNASSIGNED",
  PENDING_VENDOR_REVIEW: "PENDING_VENDOR_REVIEW",
  REJECTED_BY_VENDOR: "REJECTED_BY_VENDOR",
  IN_PRODUCTION: "IN_PRODUCTION",
  FINISHING: "FINISHING",
  READY_FOR_QC: "READY_FOR_QC",
  QC_IN_REVIEW: "QC_IN_REVIEW",
  QC_FAILED: "QC_FAILED",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",
  DISPATCHED: "DISPATCHED",
  COMPLETED_ARCHIVED: "COMPLETED_ARCHIVED",
});

export const PriorityLevel = Object.freeze({
  STANDARD: "Standard",
  HIGH: "High Priority",
  EXPRESS: "Express",
  URGENT: "URGENT",
});
